### ISSUE TITLE
Outcomes meeting 17/10 - Poster

### ISSUE THREAD

**Issue by amartinhuertas** [GiteonCaulfied/COMP4560_stokes_ml_project#12]
- Address @sghelichkhani 's comments (https://github.com/GiteonCaulfied/COMP4560_stokes_ml_project/issues/11)
- Move the current bullet points in the introduction-Motivation as paragraphs to the project report. Reduce the amount of text in this poster's section. I have the impression that part of the current sentences in these paragraphs can be refactored in the subsection below entitled "Mantle Convection Problem".
- Use geoid with lower case g except those standard points where upper case G is needed.
- Figure 2. 
  * Substitute equations by the one provided by Sia's. 
  * Replace Parameters box by a picture of the initial temperature field.  
  * Label the box on the left with "initial temperature", and the box on the right  with "temperature time evolution predicted by numerical solver" [For simplicity, perhaps we can skip the illustration about the random generation of initial conditions by sampling a probability distribution, or we can have it in the data set section, if we believe it's going to be necessary, helpful]
- Research aims of the Mantle Convection Problem @sghelichkhani 
- "Methods (Continue)". "Two ways ..."->"Two possible ways ..."
- Figure 7. Try to find a more serious reference to the figure on the left. If not possible, replace in the caption. "Source of the left figure: StackOverflow".
- Rewrite "The maximum value of S that is not significantly affecting accuracy should be 4 since the sum of loss and the sum of POD (Proper Orthogonal Decomposition) difference tend to have a rapid increase when S is increased from 4 to 8." by "The growth of the loss function (accuracy degradation) with S is remarkably moderate, with only a few outliers deviating moderately from the median". If we can replace "remarkably moderate" by  an estimated "rate of growth" experimentally determined, much better. @rhyshawkins 
- Future works (Mantle convection).
  * To further investigate the outliers in Figure 11 to see whether a common pattern can be identified.
  * Consider more complex physics (e.g., non-linear constitutive laws) in the Mantle convection model.
  *  To investigate to which extent the current surrogate forward models are accurate enough to end up with sensible, application experts-certified solutions to the inverse Mantle Convection problem.

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas,



> As a general comment, I suggest that you look at the output provided by the latex compiler on screen from time to time.
> 
> Looking there I could see the warning:
> 
> ```
> LaTeX Warning: There were multiply-defined labels.
> ```

This has been fixed.

Also, I've now made this repository public and refer to it in my report in the Acknowledgement chapter, as we discussed in our previous meeting.
